#Server properties
server.port=8080
spring.application.name=desafio-tinnova

#Database properties
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

#Hibernate/JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#Security
api.security.token.secret=9xW7vA2bZ5mK3pQ8eR1tY6uI4oP0sD7fG2hJ5kL8
